### ISSUE TITLE
Add Relative Performance Chart Method

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-returns#13]
This method should calculate the relative portfolio performance over time. The result will be visually compared to the performance in indizes like MSCI World or S&P500.

In my head, this method accepts an array of values (e.g. the value history) and calculates each position as a %-change to the first entry.

```
[5, 10, 50, -10]
```
becomes
```
[?, 100%, 900%, -300%]
```

I'm not 100% certain this is the correct way to calculate it and I'm not sure about the first value.

**Comment by rubensstarke** [comment]
I think that calculation should be the % change of last entry if we talking about patrimony.

for example in 01/01/2020 i have 10 then in 02/01/2020 i have 20 its will be a 100% increase, but if on 03/01/2020 i go back to 10 i have lost 50% and no 100%, make sense?

**Comment by codeofsumit** [comment]
From what I see in various brokers, I think the relative % should always be vs the number at the start of the interval. If you look at charts like these, they always start at 0% (starting value) and every other value on the chart is against that starting value:

![image](https://user-images.githubusercontent.com/2399810/98913065-2dc66280-24c7-11eb-80f7-0654ee828e34.png)

![image](https://user-images.githubusercontent.com/2399810/98913121-40409c00-24c7-11eb-9194-0d65d53c627b.png)

So the calculation is actually quite easy. The method recieves an array of values (e.g. the value history of a chart) and calculates relative % numbers to the first value

**Comment by codeofsumit** [comment]
done
