### ISSUE TITLE
Idea to improve perf of normalizeQuotes changing the quotes array

### ISSUE THREAD

**Issue by rubensstarke** [codeofsumit/tresor-returns#4]
![image](https://user-images.githubusercontent.com/4966360/97256817-da7bc100-17f2-11eb-8669-bb3d3a01f131.png)

The idea is: instead find by date, we change the quotes to have the date as key of object, possibilities direct access to value.

@felixheck make sense?

**Comment by felixheck** [comment]
LGTM, so just one iteration is needed.

**Comment by rubensstarke** [comment]
wip

**Comment by rubensstarke** [comment]
@felixheck and @codeofsumit  take a look:

i changed the quotes.json to something like this:
![quotes-changed](https://user-images.githubusercontent.com/4966360/97506119-f7320900-1958-11eb-96eb-871a21a3c3e7.png)
dates as a key, point if you think that just the date is not enough to make it unique inside a holding

then i change inside normalizeQuotes to use just t as key in quotes:
![using](https://user-images.githubusercontent.com/4966360/97506248-424c1c00-1959-11eb-9710-00b869babfff.png)

the benchmark goes from ~2400ms to ~930ms:
![quotes-date](https://user-images.githubusercontent.com/4966360/97506319-6c9dd980-1959-11eb-80ec-8db806b1bda7.png)



Make sense?

i created this script to convert quotes.json to quotesChanged.json :t-rex: 
![image](https://user-images.githubusercontent.com/4966360/97506442-aec71b00-1959-11eb-9449-414c3a49ce0a.png)

**Comment by felixheck** [comment]
@codeofsumit should we run [`_.keyBy`](https://lodash.com/docs/4.17.15#keyBy) outside this function or inside? Think that kind of new structure is needed nowhere else.

**Comment by codeofsumit** [comment]
let's do it inside

**Comment by rubensstarke** [comment]
#6
